################################################################
# Global configuration
################################################################
port = ":80"

################################################################
# Web configuration backend
################################################################

[web]
address = ":8080"

################################################################
# Docker configuration backend
################################################################

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
swarmmode = false

